name: compile

on:
  workflow_dispatch:
  pull_request:
    paths:
      - nas-common/**
      - nas-deploy/**
      - nas-music/**
      - nas-video/**
      - pom.xml
  push:
    paths:
      - nas-common/**
      - nas-deploy/**
      - nas-music/**
      - nas-video/**
      - pom.xml

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 21
        uses: actions/setup-java@v2
        with:
          distribution: 'zulu'
          java-version: 21

      - name: Cache local Maven repository
        uses: actions/cache@v2
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-
      - name: compile with Maven
        run: mvn -B compile --file pom.xml
